baseURL = "http://localhost:3000/"
languageCode = "en-us"
theme = "paper"
title = "Test_v2_site"

[params]
bio = "A blog powered by Siru"
color = "linen"
disableHLJS = true
disablePostNavigation = true
localKatex = false
math = true
monoDarkIcon = true
